// File: build.gradle (a livello di progetto)
// ---------- CODICE MODIFICATO E OTTIMIZZATO ----------

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        // --- AGGIUNTO IL REPOSITORY PER MPANDROIDCHART ---
        maven { url 'https://www.jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}