// Top-level build file
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Questa riga deve corrispondere alla tua versione di Android Studio
        classpath 'com.android.tools.build:gradle:9.0.0'
    }
}

plugins {
    id 'com.android.application' version '9.0.0' apply false
}

// ABBIAMO RIMOSSO "allprojects": i repository sono ora gestiti centralmente in settings.gradle

task clean(type: Delete) {
    delete rootProject.buildDir
}