name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Aggiunto il trigger per l'avvio manuale

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      run: ./gradlew build
